version: '3.7'

services:
  smoke-test:
    # image: golang:1.19.3-buster
    # container_name: smoke-test
    # working_dir: /app
    # ports:
    #   - 8080:8080
    # volumes:
    #   - .:/app
    # command: go run main.go
    build: .
    container_name: smoke-test
    ports:
      # map port 8080 on the host to port 9080 in the container
      - 9080:9080
    volumes:
      - .:/app
    command: go run main.go
